package com.icash.icash_enum;

public enum  ProviderType {
    OFFER_TORO, SUPER_REWARDS, SAMPLE_CUBE, PEANUT_LABS, PTC_WALL, RADIO_LOYALTY, TOKEN_ADS, ENGAGEME_TV, OFFER_VAULT, OGADS, PROLEADS_MEDIA
}
